Advanced bot - Minimum features | Almost everything changed
Gamearoos-development/liberty-bot pull request #5
Opened 2022-03-13 20:14 UTC by TheDogHusky

——————
Liberty Bot
——————
> What’s new?

> New commands, new categories. Linked to mongodb and customizable prefix setup.
> Handler changed, and corrected some bugs.
> Logger linked to client (client.logger)

2022-03-13 20:22 UTC, GamearooCodes requested changes
Fix any problems i mentioned in the review

2022-03-13 20:22 UTC, GamearooCodes commented on src/commands/Info/clientinfo.js
> +	async command(bot, message, args, extras, data) {
data can you explain what its used for and why it cant be part of extras?

2022-03-13 20:22 UTC, GamearooCodes commented on src/commands/Info/ping.js
> +        } else if(botPing >= 300) {
remove bad to us stable is 600 and below and lag is 600 and above

2022-03-13 20:22 UTC, GamearooCodes commented on src/commands/Info/ping.js
> +            apiPingCommentaire = 'Bad';
remove bad to us stable is 600 and below and lag is 600 and above

2022-03-13 20:22 UTC, GamearooCodes commented on src/commands/Mod/ban.js
> +        message.reply({ content: `${member.user.tag} has been banned for reason: \`${reason}\``, allowedMentions: { repliedUser: false } })
add a logs system to a channel if you can

2022-03-13 20:22 UTC, GamearooCodes commented on src/commands/Utils/avatar.js
> +        const optionnalMember = message.mentions.members.first();
please remove this command we do not collect or send data that a user can abuse to do illegal or breaking tos with

2022-03-13 20:22 UTC, GamearooCodes commented on src/events/msg.js
>  			hello: "Hello",
if you can move data to the extras to pass it into commands ty

2022-03-13 20:25 UTC, TheDogHusky commented on src/commands/Info/clientinfo.js
> +	async command(bot, message, args, extras, data) {
Data represents the GuildSchema. Yeah I can import it in extras

2022-03-13 20:25 UTC, TheDogHusky commented on src/commands/Info/ping.js
> +            apiPingCommentaire = 'Bad';
I’ll change it webnesday

2022-03-13 20:26 UTC, TheDogHusky commented on src/commands/Mod/ban.js
> +        message.reply({ content: `${member.user.tag} has been banned for reason: \`${reason}\``, allowedMentions: { repliedUser: false } })
Just a channel send to a special property in the schema? Like I do a log system? Okay I’ll do that too

2022-03-13 20:26 UTC, TheDogHusky commented on src/commands/Utils/avatar.js
> +        const optionnalMember = message.mentions.members.first();
K

2022-03-13 20:26 UTC, TheDogHusky commented on src/events/msg.js
>  			hello: "Hello",
Okay I’ll change it

2022-03-13 20:27 UTC, GamearooCodes commented on src/commands/Mod/ban.js
> +        message.reply({ content: `${member.user.tag} has been banned for reason: \`${reason}\``, allowedMentions: { repliedUser: false } })
yes a embed of the log of who banned it and not maybe make a setting to enable/disable the log

2022-03-14 17:37 UTC, TheDogHusky commented on src/commands/Mod/ban.js
> +        message.reply({ content: `${member.user.tag} has been banned for reason: \`${reason}\``, allowedMentions: { repliedUser: false } })
maybe a setting just to enable or disable the mod logs

2022-03-16 15:43 UTC, TheDogHusky commented
The log system has been added, I let you review the pull request!

2022-03-17 02:32 UTC, GamearooCodes requested changes
please fix the package manager issues

2022-03-17 02:32 UTC, GamearooCodes commented on package.json
> +		"yarn": "^1.22.17"
please remove yarn and use npm i -g yarn or change the package manager to npm

2022-03-17 09:21 UTC, TheDogHusky commented on package.json
> +		"yarn": "^1.22.17"
why? Yarn is already installed and works perfectly

2022-03-17 09:22 UTC, TheDogHusky commented on package.json
> +		"yarn": "^1.22.17"
![image](https://user-images.githubusercontent.com/74465875/158778168-612fcbf2-68df-485d-922f-1ececdde695b.png)
it's already fixed btw

2022-03-17 09:23 UTC, TheDogHusky commented on package.json
> +		"yarn": "^1.22.17"
there is no packager issue idk why it's like that on github

2022-03-17 09:33 UTC, merged